kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: redhat-operators-catalogs
spec:
  dockerImageRepository: registry.redhat.io/redhat/redhat-operator-index
  tags:
  - name: v4.8
    from:
      kind: DockerImage
      name: 'registry.redhat.io/redhat/redhat-operator-index:v4.8'
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source