kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-oauth-apiserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: openshift-oauth-apiserver
  progressDeadlineSeconds: 600
  template:
    metadata:
      name: openshift-oauth-apiserver
      labels:
        app: openshift-oauth-apiserver
        clusterID: "{{ .ClusterID }}"
    spec:
      imagePullSecrets:
      - name: pull-secret
      automountServiceAccountToken: false
      containers:
      - name: oauth-apiserver
        readinessProbe:
          httpGet:
            path: readyz
            port: 8443
            scheme: HTTPS
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        command:
        - /usr/bin/oauth-apiserver
        ports:
        - containerPort: 8443
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: audit-policy
          mountPath: /var/run/audit
        - name: secret
          mountPath: /var/run/secret
        - name: config
          mountPath: /var/run/config
        - name: audit-dir
          mountPath: /var/log/oauth-apiserver
        terminationMessagePolicy: FallbackToLogsOnError
        image: {{ imageFor "oauth-apiserver" }}
        args:
        - start
        - --authentication-kubeconfig=/var/run/secret/kubeconfig
        - --authorization-kubeconfig=/var/run/secret/kubeconfig
        - --kubeconfig=/var/run/secret/kubeconfig
        - --secure-port=8443
        - --audit-log-path=/var/log/oauth-apiserver/audit.log
        - --audit-log-format=json
        - --audit-log-maxsize=100
        - --audit-log-maxbackup=10
        - --etcd-cafile=/var/run/config/etcd-ca.crt
        - --etcd-keyfile=/var/run/secret/etcd-client.key
        - --etcd-certfile=/var/run/secret/etcd-client.crt
        - --shutdown-delay-duration=3s
        - --tls-private-key-file=/var/run/secret/server.key
        - --tls-cert-file=/var/run/secret/server.crt
        - --audit-policy-file=/var/run/audit/policy.yaml
        - --cors-allowed-origins='//127\.0\.0\.1(:|$)'
        - --cors-allowed-origins='//localhost(:|$)'
        - --etcd-servers=https://{{ .EtcdClientName }}:2379
        - --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - --tls-min-version=VersionTLS12
        - --v=2
      volumes:
      - name: audit-policy
        configMap:
          name: openshift-oauth-apiserver-auditpolicy
          defaultMode: 420
      - name: secret
        secret:
          secretName: openshift-oauth-apiserver
          defaultMode: 420
      - name: config
        configMap:
          name: openshift-oauth-apiserver
          defaultMode: 420
      - name: audit-dir
        emptyDir: {}
