apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-controller-manager
data:
  root-ca.crt: |-
{{ include_pki "combined-ca.crt" 4 }}
  service-ca.crt: |-
{{ include_pki "combined-ca.crt" 4 }}
{{- if eq .CloudProvider "aws" }}
  aws.conf: |-
{{ include "aws/aws.conf" 4 }}
{{- end}}
